#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="schoolSystem")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    partial void InsertTurma(Turma instance);
    partial void UpdateTurma(Turma instance);
    partial void DeleteTurma(Turma instance);
    partial void InsertMateria(Materia instance);
    partial void UpdateMateria(Materia instance);
    partial void DeleteMateria(Materia instance);
    partial void InsertNotas(Notas instance);
    partial void UpdateNotas(Notas instance);
    partial void DeleteNotas(Notas instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Model.Properties.Settings.Default.schoolSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Aluno
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
		
		public System.Data.Linq.Table<Turma> Turma
		{
			get
			{
				return this.GetTable<Turma>();
			}
		}
		
		public System.Data.Linq.Table<Materia> Materia
		{
			get
			{
				return this.GetTable<Materia>();
			}
		}
		
		public System.Data.Linq.Table<Notas> Notas
		{
			get
			{
				return this.GetTable<Notas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aluno")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAluno;
		
		private string _Nome;
		
		private string _Endereco;
		
		private string _Cep;
		
		private string _Telefone;
		
		private string _Celular;
		
		private System.Nullable<System.DateTime> _dataNascimento;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _dataAtualizacao;
		
		private EntitySet<Notas> _Notas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAlunoChanging(int value);
    partial void OnidAlunoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCepChanging(string value);
    partial void OnCepChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OndataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OndataNascimentoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OndataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAtualizacaoChanged();
    #endregion
		
		public Aluno()
		{
			this._Notas = new EntitySet<Notas>(new Action<Notas>(this.attach_Notas), new Action<Notas>(this.detach_Notas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAluno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAluno
		{
			get
			{
				return this._idAluno;
			}
			set
			{
				if ((this._idAluno != value))
				{
					this.OnidAlunoChanging(value);
					this.SendPropertyChanging();
					this._idAluno = value;
					this.SendPropertyChanged("idAluno");
					this.OnidAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(255)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cep", DbType="VarChar(17)")]
		public string Cep
		{
			get
			{
				return this._Cep;
			}
			set
			{
				if ((this._Cep != value))
				{
					this.OnCepChanging(value);
					this.SendPropertyChanging();
					this._Cep = value;
					this.SendPropertyChanged("Cep");
					this.OnCepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(17)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(17)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataNascimento", DbType="Date")]
		public System.Nullable<System.DateTime> dataNascimento
		{
			get
			{
				return this._dataNascimento;
			}
			set
			{
				if ((this._dataNascimento != value))
				{
					this.OndataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._dataNascimento = value;
					this.SendPropertyChanged("dataNascimento");
					this.OndataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAtualizacao
		{
			get
			{
				return this._dataAtualizacao;
			}
			set
			{
				if ((this._dataAtualizacao != value))
				{
					this.OndataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._dataAtualizacao = value;
					this.SendPropertyChanged("dataAtualizacao");
					this.OndataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Notas", Storage="_Notas", ThisKey="idAluno", OtherKey="idAluno")]
		public EntitySet<Notas> Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				this._Notas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turma")]
	public partial class Turma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTurma;
		
		private int _idMateria;
		
		private string _Nome;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private EntitySet<Notas> _Notas;
		
		private EntityRef<Materia> _Materia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTurmaChanging(int value);
    partial void OnidTurmaChanged();
    partial void OnidMateriaChanging(int value);
    partial void OnidMateriaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    #endregion
		
		public Turma()
		{
			this._Notas = new EntitySet<Notas>(new Action<Notas>(this.attach_Notas), new Action<Notas>(this.detach_Notas));
			this._Materia = default(EntityRef<Materia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTurma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTurma
		{
			get
			{
				return this._idTurma;
			}
			set
			{
				if ((this._idTurma != value))
				{
					this.OnidTurmaChanging(value);
					this.SendPropertyChanging();
					this._idTurma = value;
					this.SendPropertyChanged("idTurma");
					this.OnidTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateria", DbType="Int NOT NULL")]
		public int idMateria
		{
			get
			{
				return this._idMateria;
			}
			set
			{
				if ((this._idMateria != value))
				{
					if (this._Materia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMateriaChanging(value);
					this.SendPropertyChanging();
					this._idMateria = value;
					this.SendPropertyChanged("idMateria");
					this.OnidMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turma_Notas", Storage="_Notas", ThisKey="idTurma", OtherKey="idTurma")]
		public EntitySet<Notas> Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				this._Notas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Turma", Storage="_Materia", ThisKey="idMateria", OtherKey="idMateria", IsForeignKey=true)]
		public Materia Materia
		{
			get
			{
				return this._Materia.Entity;
			}
			set
			{
				Materia previousValue = this._Materia.Entity;
				if (((previousValue != value) 
							|| (this._Materia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Materia.Entity = null;
						previousValue.Turma.Remove(this);
					}
					this._Materia.Entity = value;
					if ((value != null))
					{
						value.Turma.Add(this);
						this._idMateria = value.idMateria;
					}
					else
					{
						this._idMateria = default(int);
					}
					this.SendPropertyChanged("Materia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.Turma = this;
		}
		
		private void detach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.Turma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materia")]
	public partial class Materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMateria;
		
		private string _Nome;
		
		private string _Descricao;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _dataAtualizacao;
		
		private EntitySet<Turma> _Turma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMateriaChanging(int value);
    partial void OnidMateriaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OndataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAtualizacaoChanged();
    #endregion
		
		public Materia()
		{
			this._Turma = new EntitySet<Turma>(new Action<Turma>(this.attach_Turma), new Action<Turma>(this.detach_Turma));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMateria
		{
			get
			{
				return this._idMateria;
			}
			set
			{
				if ((this._idMateria != value))
				{
					this.OnidMateriaChanging(value);
					this.SendPropertyChanging();
					this._idMateria = value;
					this.SendPropertyChanged("idMateria");
					this.OnidMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAtualizacao
		{
			get
			{
				return this._dataAtualizacao;
			}
			set
			{
				if ((this._dataAtualizacao != value))
				{
					this.OndataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._dataAtualizacao = value;
					this.SendPropertyChanged("dataAtualizacao");
					this.OndataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Turma", Storage="_Turma", ThisKey="idMateria", OtherKey="idMateria")]
		public EntitySet<Turma> Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				this._Turma.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Turma(Turma entity)
		{
			this.SendPropertyChanging();
			entity.Materia = this;
		}
		
		private void detach_Turma(Turma entity)
		{
			this.SendPropertyChanging();
			entity.Materia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notas")]
	public partial class Notas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idNotas;
		
		private int _idTurma;
		
		private int _idAluno;
		
		private System.Nullable<float> _a1;
		
		private System.Nullable<float> _a2;
		
		private System.Nullable<float> _a3;
		
		private System.Nullable<float> _media;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Turma> _Turma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNotasChanging(int value);
    partial void OnidNotasChanged();
    partial void OnidTurmaChanging(int value);
    partial void OnidTurmaChanged();
    partial void OnidAlunoChanging(int value);
    partial void OnidAlunoChanged();
    partial void Ona1Changing(System.Nullable<float> value);
    partial void Ona1Changed();
    partial void Ona2Changing(System.Nullable<float> value);
    partial void Ona2Changed();
    partial void Ona3Changing(System.Nullable<float> value);
    partial void Ona3Changed();
    partial void OnmediaChanging(System.Nullable<float> value);
    partial void OnmediaChanged();
    #endregion
		
		public Notas()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Turma = default(EntityRef<Turma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNotas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idNotas
		{
			get
			{
				return this._idNotas;
			}
			set
			{
				if ((this._idNotas != value))
				{
					this.OnidNotasChanging(value);
					this.SendPropertyChanging();
					this._idNotas = value;
					this.SendPropertyChanged("idNotas");
					this.OnidNotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTurma", DbType="Int NOT NULL")]
		public int idTurma
		{
			get
			{
				return this._idTurma;
			}
			set
			{
				if ((this._idTurma != value))
				{
					if (this._Turma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTurmaChanging(value);
					this.SendPropertyChanging();
					this._idTurma = value;
					this.SendPropertyChanged("idTurma");
					this.OnidTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAluno", DbType="Int NOT NULL")]
		public int idAluno
		{
			get
			{
				return this._idAluno;
			}
			set
			{
				if ((this._idAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAlunoChanging(value);
					this.SendPropertyChanging();
					this._idAluno = value;
					this.SendPropertyChanged("idAluno");
					this.OnidAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a1", DbType="Real")]
		public System.Nullable<float> a1
		{
			get
			{
				return this._a1;
			}
			set
			{
				if ((this._a1 != value))
				{
					this.Ona1Changing(value);
					this.SendPropertyChanging();
					this._a1 = value;
					this.SendPropertyChanged("a1");
					this.Ona1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a2", DbType="Real")]
		public System.Nullable<float> a2
		{
			get
			{
				return this._a2;
			}
			set
			{
				if ((this._a2 != value))
				{
					this.Ona2Changing(value);
					this.SendPropertyChanging();
					this._a2 = value;
					this.SendPropertyChanged("a2");
					this.Ona2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a3", DbType="Real")]
		public System.Nullable<float> a3
		{
			get
			{
				return this._a3;
			}
			set
			{
				if ((this._a3 != value))
				{
					this.Ona3Changing(value);
					this.SendPropertyChanging();
					this._a3 = value;
					this.SendPropertyChanged("a3");
					this.Ona3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media", DbType="Real")]
		public System.Nullable<float> media
		{
			get
			{
				return this._media;
			}
			set
			{
				if ((this._media != value))
				{
					this.OnmediaChanging(value);
					this.SendPropertyChanging();
					this._media = value;
					this.SendPropertyChanged("media");
					this.OnmediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Notas", Storage="_Aluno", ThisKey="idAluno", OtherKey="idAluno", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Notas.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Notas.Add(this);
						this._idAluno = value.idAluno;
					}
					else
					{
						this._idAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turma_Notas", Storage="_Turma", ThisKey="idTurma", OtherKey="idTurma", IsForeignKey=true)]
		public Turma Turma
		{
			get
			{
				return this._Turma.Entity;
			}
			set
			{
				Turma previousValue = this._Turma.Entity;
				if (((previousValue != value) 
							|| (this._Turma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Turma.Entity = null;
						previousValue.Notas.Remove(this);
					}
					this._Turma.Entity = value;
					if ((value != null))
					{
						value.Notas.Add(this);
						this._idTurma = value.idTurma;
					}
					else
					{
						this._idTurma = default(int);
					}
					this.SendPropertyChanged("Turma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
